### ISSUE TITLE
64-bit support?

### ISSUE THREAD

**Issue by ishuo** [davepeck/iOS-libarchive#12]
We noticed that Apple made an announcement, that beginning early next year, only app submissions with 64-bit support will be accepted ([link](https://developer.apple.com/news/?id=10202014a)).

Therefore we'd like to know that, will 64-bit support be added to this project?

We tried compiling the project with 64-bit enabled, but got a lot of warnings. We're not sure what to do with the warnings. In any cases, since you know much more about libarchive and C, your opinions will be greatly appreciated!

**Comment by davepeck** [comment]
I'm finally going to get back to this library this week. I plan to update to lib archive 3; we'll see how 64-bit clean that is (or isn't).

**Comment by ishuo** [comment]
Wow that would be awesome :+1: what version of libarchive is currently being used?

**Comment by davepeck** [comment]
This repository uses libarchive2, which was the new hotness when I put it together in... 2011! :-)

**Comment by achelsmar** [comment]
Are there any updates on this? The 1st June [Link](https://developer.apple.com/news/?id=12172014b) is coming closer 🙈.

**Comment by sebastianf** [comment]
Any updates? please!

**Comment by FigBug** [comment]
There is 64 bit support now. You'll need to build the binaries yourself with the build.sh script

**Comment by davepeck** [comment]
Hi @FiBug @sebastianf @achelsmar @ishuo After looking into what it takes to get `libarchive` 3 built as a Framework in the modern iOS era (iOS 8 and 9), it turns out it's really pretty easy these days. I put up some instructions here: https://gist.github.com/davepeck/2be7c233b3baa98f1b9c &mdash; and I'm going to go ahead and delete my `iOS-libarchive` entirely, since it no longer adds value.
