### ISSUE TITLE
libarchive3 support?

### ISSUE THREAD

**Issue by ishifes** [davepeck/iOS-libarchive#13]
Hello,

Now, Stable release is libarchive-3.1.2 .
I want to use libarchive3.
Because it is necessary to deal with lha/lzh in our application.
lha/lzh (read only, starting in libarchive 3.0)

Is there something good way?

Thanks for taking care of it.

**Comment by davepeck** [comment]
Good to know. I will see what it takes to do this. Frankly, this github repo is woefully out of date at the moment... needs some love from me.

**Comment by davepeck** [comment]
Marking as **up next** -- I want to get back to this.

**Comment by davepeck** [comment]
Hi @ishifes Thank you for the issue. After looking into what it takes to get `libarchive` 3 built as a Framework in the modern iOS era (iOS 8 and 9), it turns out it's really pretty easy these days. I put up some instructions here: https://gist.github.com/davepeck/2be7c233b3baa98f1b9c &mdash; and I'm going to go ahead and delete my `iOS-libarchive` entirely, since it no longer adds value.
