### ISSUE TITLE
bitcode support?

### ISSUE THREAD

**Issue by bryanheitman** [davepeck/iOS-libarchive#16]
Could you modify build.sh to work with bitcode in Xcode7?

**Comment by davepeck** [comment]
This repo hasn't seen any love in _years_. I would love for someone to take it over at this point.

**Comment by davepeck** [comment]
Hi @bryanheitman Thank you for the pull request. After looking into what it takes to get `libarchive` 3 built as a Framework in the modern iOS era (iOS 8 and 9), it turns out it's really pretty easy these days. I put up some instructions here: https://gist.github.com/davepeck/2be7c233b3baa98f1b9c &mdash; and I'm going to go ahead and delete my `iOS-libarchive` entirely, since it no longer adds value. That said, I don't precisely know what it takes to support bitcode here -- that's one of the TODO items on the instructions I made, and I'd love your input if you figure it out!
